title: aznets
description: Research
show_downloads: false
google_analytics:
theme: jekyll-theme-architect
is_user_page: true
github:
  owner_url: https://aznets.github.io/
  ml_url: https://aznets.github.io/ml/
  dl_url: https://aznets.github.io/dl/
  radiomics_url: https://aznets.github.io/radiomics/
  research_url: https://aznets.github.io/research/
  lecture_url: https://aznets.github.io/Main/
